# Generated by Django 4.2.3 on 2024-08-30 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pid',
            field=models.CharField(default='5bgf5g151b', max_length=20, unique=True),
        ),
    ]
