# Generated by Django 4.2.3 on 2024-08-30 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_post_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pid',
            field=models.CharField(default='2aa4hhf2aa', max_length=20, unique=True),
        ),
    ]
